# docker-compose.timescale.yml

version: '3.7'
services:
  timescale:
    image: timescale/timescaledb:2.0.0-pg12
    volumes: 
      - type: volume
        # source: timescale-db # the volume name
        source: timescale_volume
        # target: the location in the container where the data are stored
        target: /var/lib/postgresql/data 
        read_only: false
      # Custom postgresql.conf file will be mounted (see command: as well)
      - type: bind
        source: ./postgresql_custom.conf
        target: /postgresql_custom.conf
        read_only: false
    env_file: .env
    environment: 
      POSTGRES_HOST: timescale
    command: ["-c", "config_file=/postgresql_custom.conf"]
    ports: 
      - 0.0.0.0:5434:5432
    networks:
      timescale_network:
    deploy:
      restart_policy:
        condition: on-failure

  app:
    build:
       context: ./
    command: gunicorn app:app --bind 0.0.0.0:5000 -k uvicorn.workers.UvicornWorker
    # expose:
    #   - 5000d
    ports:
      - 0.0.0.0:5000:5000
    networks:
      timescale_network:

# Creates a named volume to persist our database data
volumes:
  timescale_volume:

# Joins our external network
networks:
  timescale_network:
    # external: true